### ISSUE TITLE
its saying invalid code when code is correct

### ISSUE THREAD

**Issue by mohitjoshi155** [JavSensei/pcloud-dl#1]
is script not working anymore?

**Comment by JavSensei** [comment]
Hello! I just installed the package and tested it with the link in the readme and a new file I created to test it, and it still works fine. 
Just in case the code refers to the code that appears in the public link 

For 

 `https://u.pcloud.link/publink/show?code=XZtTpwVZnMvzSRIY2vhs6zCQgfHtI8Oya3YV`

 the code is 

 `XZtTpwVZnMvzSRIY2vhs6zCQgfHtI8Oya3YV`

**Comment by JavSensei** [comment]
And it also only works with files, not folders at the moment

**Comment by mohitjoshi155** [comment]
> Hello! I just installed the package and tested it with the link in the readme and a new file I created to test it, and it still works fine. Just in case the code refers to the code that appears in the public link
> 
> For
> 
> `https://u.pcloud.link/publink/show?code=XZtTpwVZnMvzSRIY2vhs6zCQgfHtI8Oya3YV`
> 
> the code is
> 
> `XZtTpwVZnMvzSRIY2vhs6zCQgfHtI8Oya3YV`

my link starts with e.pcloud and didnt work...can you try https://e.pcloud.link/publink/show?code=XZwUf1ZJUVHqzq9rsu6QuQRwruai70bWYu7
as far as i understand your script takes code from links and uses it for getpublinkdownload so it should not matter whether url starts with u or e...i have opened this issue on pcloud also regarding this

**Comment by JavSensei** [comment]
Thanks for giving more details, I read the API documentation and apparently it depends on where the user is registered, there are two endpoints "e" for Europe and "u" for the United States, https://eapi.pcloud.com/ and https://api.pcloud.com/ respectively, I had not noticed this detail I'll add it right away

**Comment by JavSensei** [comment]
@mohitjoshi155 All ready! You can now try the new version and let me know if it worked for you
`pip install pcloud-dl==0.1.8`

**Comment by mohitjoshi155** [comment]
> @mohitjoshi155 All ready! You can now try the new version and let me know if it worked for you `pip install pcloud-dl==0.1.8`

Its working
Thanks for replying and solving it so quickly
